### ISSUE TITLE
Shortcut keys should check for modifiers

### ISSUE THREAD

**Issue by gijsk** [fitzgen/bugzilla-todos#12]
STR: (tried on mac, but I suspect the problem will be the same on other OS's)
- go on any view other than "to check in"
- select some text
- hit accel+c

Expected results: copy the text
Actual results: switch to the "to check in" view.

**Comment by harthur** [comment]
Oh wow, thanks for reporting.

**Comment by harthur** [comment]
Should be fixed in eda08c04

**Comment by gijsk** [comment]
Brilliant, thanks!
