### ISSUE TITLE
Don't show bugs with [fixed-in-...] as 'To Fix'

### ISSUE THREAD

**Issue by gijsk** [fitzgen/bugzilla-todos#17]
My "To Fix" list used to be pretty short, but yesterday or the day before it seems bugmotodo was updated and now it shows all the bugs I've fixed on the UX branch (which isn't merging for a little while...) and are marked as [fixed-in-ux]. This makes me sad because I can no longer distill a useful 'todo' list from it. :-(

I looked through the changes in the last 3 months but didn't see an explicit change in this filtering... maybe I missed it? Was this deliberate, and if so, could we (shudder) have an option to enable/disable this behaviour?

**Comment by harthur** [comment]
Interesting. This line should be taking that case: https://github.com/harthur/bugzilla-todos/blob/gh-pages/app/user.js#L110. Maybe it's Bugzilla's fault then?

**Comment by gijsk** [comment]
Console says the request that bugmotodo is making is going to: https://api-dev.bugzilla.mozilla.org/latest//bug?email1=gijskruitbosch%2Bbugs%40gmail.com&email1_type=equals&email1_assigned_to=1&order=changeddate%20DESC&status=NEW&status=UNCONFIRMED&status=REOPENED&status=ASSIGNED&include_fields=id%2Csummary%2Cstatus%2Cresolution%2Clast_change_time%2Cattachments

That doesn't seem to have those parameters. :S

**Comment by gijsk** [comment]
Which makes sense, because the link you posted is for needsCheckin. I was wondering about "To Fix", which I believe is this code: https://github.com/harthur/bugzilla-todos/blob/gh-pages/app/user.js#L241 ?

**Comment by harthur** [comment]
Think this is fixed now.
