### ISSUE TITLE
"To Review" does not show Feedback requests

### ISSUE THREAD

**Issue by robcee** [fitzgen/bugzilla-todos#19]
Feedback is important. At least as important as official reviews because it is often used as a preliminary sanity check. "Does this code look ok? Should I keep going with it?"

We should add Feedback requests to the To Review section.

**Comment by nikhilm** [comment]
It does shows feedback requests in the To Review section the latest version I pulled from git and also the versions deployed on http://bugmotodo.org and github.io.

**Comment by robcee** [comment]
my bad. This was mentioned in a newsgroup post on mozilla.dev.platform so I filed it. Thanks for the clarification. Closing.

**Comment by harthur** [comment]
Always showed feedback requests along with the review requests. I hope it wasn't missing random ones...though I can't think of why it would.
