### ISSUE TITLE
Leaks memory

### ISSUE THREAD

**Issue by glandium** [fitzgen/bugzilla-todos#25]
After a couple days, my bugzilla-todos tab sucks more than 100MB according to about:memory, while it takes 9MB after closing and reopening the tab.

**Comment by harthur** [comment]
omg, I forgot about this. Thanks so much for reporting. Has to do with the periodic fetching.

**Comment by mozfreddyb** [comment]
I just found bugzilla-todos and find it overly useful, thanks. This issue worries me a bit though.
Is there a way I can help tackling this bug? I'm not really experienced in identifying/removing memory leaks but my JS/HTML is pretty good.

**Comment by harthur** [comment]
Hi, unfortunately I'm not experienced in JS memory leak debugging either. But any insights here are very welcome.

**Comment by glandium** [comment]
Still happening to me. I also get the non-responsive script alert after having the tab open for a long time. This is what about:memory says about it:
│  ├───99.28 MB (10.74%) -- top(http://harthur.github.io/bugzilla-todos/, id=21)
│  │   ├──89.15 MB (09.64%) -- active
│  │   │  ├──88.98 MB (09.63%) -- window(http://harthur.github.io/bugzilla-todos/)
│  │   │  │  ├──56.50 MB (06.11%) -- dom
│  │   │  │  │  ├──55.79 MB (06.04%) ── orphan-nodes
│  │   │  │  │  └───0.71 MB (00.08%) ++ (4 tiny)
│  │   │  │  ├──31.68 MB (03.43%) -- js-compartment(http://harthur.github.io/bugzilla-todos/)
│  │   │  │  │  ├──30.23 MB (03.27%) -- objects
│  │   │  │  │  │  ├──27.36 MB (02.96%) -- gc-heap
│  │   │  │  │  │  │  ├──17.74 MB (01.92%) ── ordinary
│  │   │  │  │  │  │  └───9.62 MB (01.04%) ++ (2 tiny)
│  │   │  │  │  │  └───2.87 MB (00.31%) ++ (2 tiny)
│  │   │  │  │  └───1.45 MB (00.16%) ++ (7 tiny)
│  │   │  │  └───0.80 MB (00.09%) ++ (3 tiny)
│  │   │  └───0.17 MB (00.02%) ++ window(about:blank)
│  │   └──10.13 MB (01.10%) ++ js-zone(0x7f12cc59d800)

That's a lot of orphaned dom nodes. And after a reload of the page (so, with the same visible content):
│  ├───20.56 MB (02.35%) -- top(http://harthur.github.io/bugzilla-todos/, id=21)
│  │   ├──11.56 MB (01.32%) -- js-zone(0x7f12cc59d800)
│  │   │  ├───9.97 MB (01.14%) ── unused-gc-things
│  │   │  └───1.59 MB (00.18%) -- (6 tiny)
│  │   │      ├──0.48 MB (00.05%) ++ strings
│  │   │      ├──0.43 MB (00.05%) ── type-pool
│  │   │      ├──0.27 MB (00.03%) ── gc-heap-arena-admin
│  │   │      ├──0.23 MB (00.03%) ++ lazy-scripts
│  │   │      ├──0.17 MB (00.02%) ── type-objects/gc-heap
│  │   │      └──0.00 MB (00.00%) ── sundries/malloc-heap
│  │   └───9.00 MB (01.03%) -- active
│  │       ├──8.84 MB (01.01%) -- window(http://harthur.github.io/bugzilla-todos/)
│  │       │  ├──5.94 MB (00.68%) -- js-compartment(http://harthur.github.io/bugzilla-todos/)
│  │       │  │  ├──3.90 MB (00.45%) -- objects
│  │       │  │  │  ├──3.45 MB (00.39%) -- gc-heap
│  │       │  │  │  │  ├──2.71 MB (00.31%) ── ordinary [2]
│  │       │  │  │  │  ├──0.64 MB (00.07%) ── function [2]
│  │       │  │  │  │  └──0.10 MB (00.01%) ── dense-array [2]
│  │       │  │  │  ├──0.46 MB (00.05%) ++ malloc-heap
│  │       │  │  │  └──0.00 MB (00.00%) ── non-heap/code/asm.js
│  │       │  │  ├──1.49 MB (00.17%) ++ shapes
│  │       │  │  ├──0.30 MB (00.03%) ++ type-inference
│  │       │  │  ├──0.22 MB (00.03%) ++ scripts
│  │       │  │  ├──0.02 MB (00.00%) ++ sundries
│  │       │  │  └──0.02 MB (00.00%) ── regexp-compartment [2]
│  │       │  ├──2.42 MB (00.28%) -- dom
│  │       │  │  ├──1.00 MB (00.11%) ── event-targets [3]
│  │       │  │  ├──0.88 MB (00.10%) ── element-nodes [2]
│  │       │  │  ├──0.50 MB (00.06%) ── text-nodes [2]
│  │       │  │  └──0.03 MB (00.00%) ── other [3]
│  │       │  ├──0.34 MB (00.04%) ++ layout
│  │       │  ├──0.13 MB (00.02%) ── style-sheets [2]
│  │       │  └──0.00 MB (00.00%) ── property-tables [2]
│  │       └──0.17 MB (00.02%) ++ window(about:blank)

**Comment by harthur** [comment]
Now fixed with React rewrite.
