### ISSUE TITLE
Don't show needinfo flags of oneself in "To Nag"

### ISSUE THREAD

**Issue by gijsk** [fitzgen/bugzilla-todos#27]
Today my bugmail inbox was heavy on unread stuff, so I needinfo'd myself on bugs I still need to respond to. I'm told I'm not the first one to be doing this.

They show up double, both in "to respond" and in "to nag". Ideally, they shouldn't be in "to nag", I think. :-)

**Comment by fitzgen** [comment]
Is this issue fixed?

**Comment by gijsk** [comment]
Uh, I think so! I don't really regularly needinfo myself... but I tested the patch I used, and it worked then, and got merged, so I'll close this. :-)
(feel free to reopen if you're still seeing this going wrong, of course...)
