### ISSUE TITLE
patches already checked in, but bug kept open with [leave-open] in "To Check In"

### ISSUE THREAD

**Issue by fitzgen** [fitzgen/bugzilla-todos#33]
If you land a patch that fixes part of a bug, but not the whole thing, and keep the bug open via whiteboarding `[leave-open]`, the bug stays in the "To Check In" section despite the patch already being checked in.

**Comment by gijsk** [comment]
Did you set checkin+ on the patch? I'm guessing we don't want the bug to never reappear in "To Check In" even when there are new patches on it that do need checking in...

**Comment by fitzgen** [comment]
I don't think I did. Will re-open if I find that doesn't fix the issue in the future.
