### ISSUE TITLE
App launch page 404s

### ISSUE THREAD

**Issue by edmorley** [fitzgen/bugzilla-todos#45]
1) Go to http://harthur.github.io/bugzilla-todos/
2) Click install app
3) Launch app

Expected:
Page resembling http://harthur.github.io/bugzilla-todos/index.html

Actual:
"404 \n There isn't a github page here"

Broken in Nightly and Firefox for Android beta.

Guessing launch_path is incorrect here:
https://github.com/harthur/bugzilla-todos/blob/gh-pages/manifest.webapp#L4

Attempts to test adjusting it locally were unsuccessful, since the Firefox's MozApps.js doesn't seem to like installing from the local filesystem, even when adjusted for absolute paths. Testing from people didn't work either, with another set of unhelpful errors, sigh.

**Comment by edmorley** [comment]
@paulrouget as the last person to touch manifest.webapp, don't suppose you can take a look? :-)

**Comment by paulrouget** [comment]
Use http://bugmotodo.org

**Comment by edmorley** [comment]
Ok, thank you :-)
(Though that pull request regressed non root directory hosting)

**Comment by harthur** [comment]
Wait,

It should work from the github url. Does it not?

**Comment by edmorley** [comment]
It doesn't for me in Nightly or Firefox for Android (per STR in comment 0).

**Comment by harthur** [comment]
I'd rather have it work on the Github page if we had to choose. Do we have to @paulrouget?

**Comment by paulrouget** [comment]
If I'm not mistaken, the launch path has to be absolute (it has to start with `/`). So we can't support both URLs at the same time.

**Comment by edmorley** [comment]
Could someone do the backout? :-)

**Comment by mcepl** [comment]
If the app is hosted in new location, somebody should update Mozilla Marketplace. App from there bombs.

**Comment by ozten** [comment]
Installing via http://bugmotodo.org/ on Nightly desktop fails for me on Linux. 404.

**Comment by harthur** [comment]
@ozten try http://harthur.github.io/bugzilla-todos/ and let me know if that doesn't work.
