### ISSUE TITLE
When refreshing, fetch currently selected tab first

### ISSUE THREAD

**Issue by gijsk** [fitzgen/bugzilla-todos#47]
I don't know if this is just the API latency (and query simplicity or lack thereof) making the queries slow, but it seems like "To Review" always loads first. It'd be nice if, should I have another tab loaded first, that one loaded before the others did

**Comment by harthur** [comment]
To Review will load faster because it takes less time for the Bugzilla server to perform that particular database query. I don't think there's anything we can do client-side to prioritize them.

**Comment by gijsk** [comment]
Depending on HTTP concurrent request limits of the browser, and how many requests we're making, it may actually make a difference which one you request first, but that might not be worth the trouble... (offhand, ISTR modern browsers have a limit of 6 concurrent requests per server, which wouldn't really be influencing this as there's presumably only 5 queries (followed by the bug queries, I suppose)).
