### ISSUE TITLE
Handle HTTP 400 errors thrown when a dependant bug is non-public

### ISSUE THREAD

**Issue by edmorley** [fitzgen/bugzilla-todos#55]
In issue #54, we throw when encountering err = "HTTP status 400", which can be caused by the bug being non-public (ie Access Denied). I'm going to file an issue against bz.js for making this case more identifiable, but for now we should handle these more elegantly.

The reason for looking at dependant bugs is to decide if the current bug is actionable, and so whether it should be excluded from the "to fix" list or not. In the case of access denied bugs (where we cannot know if they are open or resolved), we should treat them as resolved to be safe (and thus not be the cause for the current bug to be hidden, since we can't say whether it's blocked or not).

https://github.com/harthur/bugzilla-todos/blob/gh-pages/app/user.js#L316

**Comment by mozfreddyb** [comment]
After all the iterations on clarifying where the 400s are caused, I agree this is a reasonable fix (assuming hidden bugs as resolved)

**Comment by edmorley** [comment]
https://github.com/harthur/bugzilla-todos/pull/56

**Comment by edmorley** [comment]
https://github.com/harthur/bugzilla-todos/commit/145c4e13e7d36415359d02ed1f09af34090ef4e8
