### ISSUE TITLE
Fails to load bugs, exception on req.open

### ISSUE THREAD

**Issue by fitzgen** [fitzgen/bugzilla-todos#57]
No bugs load for me, I just get this enigmatic exception:

![screen shot 2014-05-13 at 4 12 23 pm](https://cloud.githubusercontent.com/assets/74571/2965376/30ad1d82-daf4-11e3-91f7-69fdb26adbb8.png)

**Comment by harthur** [comment]
Seems to be fine now. Maybe Bugzilla was down?
