### ISSUE TITLE
React warnings in console

### ISSUE THREAD

**Issue by edmorley** [fitzgen/bugzilla-todos#63]
10:58:07.946 "Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory" react-0.12.0.js:18087:6
10:58:07.946 "Warning: React.renderComponent will be deprecated in a future version. Use React.render instead." react-0.12.0.js:18087:6
10:58:07.948 "Warning: TodosApp is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory" react-0.12.0.js:18087:6
10:58:07.952 "Warning: TodoTabs is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory" react-0.12.0.js:18087:6
10:58:07.953 "Each child in an array should have a unique "key" prop. Check the render method of TabsNav. See http://fb.me/react-warning-keys for more information." react-0.12.0.js:9663:2
10:58:07.955 "Warning: TabsContent is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory" react-0.12.0.js:18087:6
10:58:07.955 "Each child in an array should have a unique "key" prop. Check the render method of TabsContent. See http://fb.me/react-warning-keys for more information." react-0.12.0.js:9663:2
10:58:07.956 "Warning: PatchList is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory" react-0.12.0.js:18087:6
10:58:07.956 "Warning: List is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory" react-0.12.0.js:18087:6
10:58:07.957 "Warning: NagList is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory" react-0.12.0.js:18087:6
10:58:07.958 "Warning: RespondList is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory" react-0.12.0.js:18087:6
10:58:07.958 "Warning: BugList is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory" react-0.12.0.js:18087:6

**Comment by harthur** [comment]
Fixed all the "Warning: Something is calling a React component directly" warnings at least.
