### ISSUE TITLE
New UI cuts columns off at the bottom

### ISSUE THREAD

**Issue by gijsk** [fitzgen/bugzilla-todos#79]
https://fitzgen.github.io/bugzilla-todos/?email=gijskruitbosch+bugs@gmail.com

The "To respond" column (currently) has enough items that the bottom item gets cut off, but there is no scrollbar.

The "To nag" column has so many items it has a really long scrollbar, but the bottom of the scrollbar is cut off by the footer of the page.

**Comment by fitzgen** [comment]
Yeah I've noticed this too, but my CSS is just so poor I couldn't figure it out :-/

**Comment by gijsk** [comment]
Fixed by #80. :-)
